spring:
  application:
    name: ecom-api-gateway

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: env,health,gateway,routes  # Gateway extras: routes, global filters
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: TRACE