spring:
  application:
    name: kafka-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,loggers
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.kafka: INFO
