spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/e-com-order-db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "tn.iteam.orderservice.dto.*"
    admin:
      properties:
        auto.create.topics.enable: true

server:
  port: 8082
  address: 0.0.0.0  # Bind to all interfaces (IPv4 + IPv6) to fix IPv6-only listen
# application.yml (order-service)
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    tn.iteam.orderservice: DEBUG
    tn.iteam.orderservice.feign: DEBUG
    tn.iteam.orderservice.service: DEBUG
    tn.iteam.orderservice.controller: DEBUG
    org.apache.kafka: DEBUG
    org.springframework.kafka: DEBUG