spring:
  application:
    name: auth-register-service

jwt:
  secret: pFagBCUehilQNym09+KkGm4DkMuW9taEC6asn3yGLULaXrziya/aZaVdd0LLZOmyJMxV8LBmwxW/9f/mxx3uDA==

app:
  upload:
    dir: /home/imed/Documents/e-commerce-ms/auth-register-service/uploads
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG  # Filter chain details
    io.jsonwebtoken: DEBUG  # JWT parse/signature errors
    tn.iteam.authregisterservice: DEBUG  # Your package (adjust if different)

