spring:
  application:
    name: catalogue-service

jwt:
  secret: pFagBCUehilQNym09+KkGm4DkMuW9taEC6asn3yGLULaXrziya/aZaVdd0LLZOmyJMxV8LBmwxW/9f/mxx3uDA==

app:
  upload:
    dir: /home/imed/Documents/stage/simple_spring_ms/catalogue-service/uploads


