spring:
  application:
    name: catalogue-service
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/e-com-catalogue-db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8084

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    metadata-map:
      zone: docker

management:
  endpoints:
    web:
      exposure:
        include: health,info
