spring:
  config:
    activate:
      on-profile: local

server:
  address: 0.0.0.0

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health







